# Generated by Django 5.2.17 on 2026-08-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('production_line', models.CharField(blank=True, default='', max_length=120)),
                ('skills_json', models.JSONField(default=list)),
                ('current_load', models.DecimalField(decimal_places=4, max_digits=5)),
                ('on_duty', models.BooleanField(default=True)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['available', 'on_duty', 'current_load'], name='staff_emplo_availab_8fb06d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('current_load__gte', 0), ('current_load__lte', 1)), name='employee_load_between_0_and_1')],
            },
        ),
    ]
