# Generated by Django 5.2.17 on 2026-08-14 02:51

import apps.workorders.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0002_alter_workorder_email_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSubmission",
            fields=[
                (
                    "submission_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "等待AI审核"),
                            ("FINALIZED", "已完成Django裁决"),
                            ("NEEDS_MORE_INFO", "需要补充材料"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=32,
                    ),
                ),
                ("client_request_id", models.CharField(max_length=120, unique=True)),
                ("report_text", models.TextField()),
                (
                    "actual_work_hours",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("parts_replaced_json", models.JSONField(default=list)),
                (
                    "source_fault_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("knowledge_package_hash", models.CharField(max_length=64)),
                (
                    "review_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COMPLETE", "建议完成"),
                            ("ABNORMAL", "建议异常报工"),
                            ("NEEDS_MORE_INFO", "需要补充材料"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "review_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("review_summary", models.TextField(blank=True, default="")),
                ("review_payload_json", models.JSONField(default=dict)),
                ("final_report_data_json", models.JSONField(default=dict)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "webhook_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "等待触发"),
                            ("SENDING", "触发中"),
                            ("DELIVERED", "已送达"),
                            ("FAILED", "触发失败"),
                            ("NOT_CONFIGURED", "未配置"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("webhook_error", models.TextField(blank=True, default="")),
                ("webhook_delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_submissions",
                        to="workorders.workorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportEvidence",
            fields=[
                (
                    "evidence_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to=apps.workorders.models.report_evidence_upload_to,
                    ),
                ),
                (
                    "original_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("content_type", models.CharField(max_length=100)),
                ("byte_size", models.PositiveBigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, default="", max_length=64)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="workorders.reportsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "created_at", "evidence_id"],
            },
        ),
        migrations.AddIndex(
            model_name="reportsubmission",
            index=models.Index(
                fields=["work_order", "status", "created_at"],
                name="workorders__work_or_26fed5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportsubmission",
            index=models.Index(
                fields=["webhook_status", "created_at"],
                name="workorders__webhook_dad436_idx",
            ),
        ),
    ]
