# Generated by Django 5.2.17 on 2026-08-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookProbe",
            fields=[
                (
                    "probe_id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("client_request_id", models.CharField(max_length=120, unique=True)),
                ("challenge", models.CharField(max_length=64)),
                ("callback_token_hash", models.CharField(max_length=64)),
                (
                    "dispatch_status",
                    models.CharField(
                        choices=[
                            ("SENDING", "发送中"),
                            ("DELIVERED", "已送达"),
                            ("FAILED", "发送失败"),
                            ("NOT_CONFIGURED", "未配置"),
                        ],
                        default="SENDING",
                        max_length=20,
                    ),
                ),
                (
                    "dispatch_http_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "dispatch_error",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("callback_received_at", models.DateTimeField(blank=True, null=True)),
                ("callback_payload_json", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["dispatch_status", "created_at"],
                        name="webhook_pro_dispatc_6dc566_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="webhook_pro_expires_b8c0a4_idx"
                    ),
                ],
            },
        ),
    ]
