# Generated by Django 5.2.17 on 2026-08-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequestRecord',
            fields=[
                ('client_request_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('object_id', models.CharField(blank=True, default='', max_length=80)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['action', 'object_id'], name='common_clie_action_f6c026_idx')],
            },
        ),
    ]
