# Generated by Django 5.2.17 on 2026-08-13 07:02

import apps.platform_probe.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mold",
            fields=[
                ("mold_id", models.CharField(max_length=40, primary_key=True, serialize=False)),
                ("mold_name", models.CharField(max_length=120)),
                (
                    "mold_type",
                    models.CharField(
                        choices=[("INJECTION", "注塑模具"), ("SHEET_METAL", "钣金模具")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PRODUCTION", "生产中"),
                            ("IN_STORAGE", "库中"),
                            ("UNDER_REPAIR", "维修中"),
                            ("DISABLED", "停用"),
                        ],
                        default="IN_PRODUCTION",
                        max_length=20,
                    ),
                ),
                ("development_tonnage", models.PositiveIntegerField(blank=True, null=True)),
                ("current_count", models.BigIntegerField(default=0)),
                ("cycle_baseline_count", models.BigIntegerField(default=0)),
                ("cycle_baseline_time", models.DateTimeField()),
                ("cycle_version", models.PositiveIntegerField(default=1)),
                ("last_production_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_reset_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MAINTENANCE_COMPLETED", "保养完成"),
                            ("REPAIR_COMPLETED", "修模完成"),
                            ("INSERT_REPLACED", "换镶件完成"),
                            ("HISTORY_IMPORTED", "历史记录导入"),
                        ],
                        default="",
                        max_length=40,
                    ),
                ),
                ("last_reset_event_id", models.CharField(blank=True, default="", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["mold_id"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceAlert",
            fields=[
                (
                    "alert_id",
                    models.CharField(
                        default=apps.platform_probe.models.new_alert_id,
                        editable=False,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("MAINTENANCE_DUE", "模次保养到期"),
                            ("TWO_MONTH_REMINDER", "注塑两个月提醒"),
                            ("IDLE_AUTO_REMINDER_DISABLED", "两年无产量停止自动提醒"),
                        ],
                        max_length=40,
                    ),
                ),
                ("cycle_version", models.PositiveIntegerField()),
                ("cycle_count_snapshot", models.BigIntegerField(default=0)),
                ("threshold_snapshot", models.PositiveIntegerField(blank=True, null=True)),
                ("trigger_basis_json", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "开放"),
                            ("WORK_ORDER_CREATED", "已创建工单"),
                            ("CLOSED", "关闭"),
                        ],
                        default="OPEN",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mold",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="platform_probe.mold",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "alert_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mold", "alert_type", "cycle_version"),
                        name="uniq_alert_per_mold_type_cycle",
                    )
                ],
            },
        ),
    ]
