# Generated by Django 5.2.17 on 2026-08-13 07:06

import apps.platform_probe.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_probe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('team', models.CharField(blank=True, default='', max_length=120)),
                ('skill_tags', models.JSONField(default=list)),
                ('available', models.BooleanField(default=True)),
                ('current_load', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('work_order_id', models.CharField(default=apps.platform_probe.models.new_work_order_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING_ASSIGNMENT', '待派工'), ('ASSIGNED', '已派工'), ('IN_PROGRESS', '进行中'), ('PAUSED', '已暂停'), ('COMPLETED', '已完成'), ('ABNORMAL_REPORTED', '异常已上报'), ('CANCELLED', '已取消')], default='PENDING_ASSIGNMENT', max_length=30)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('required_finish_at', models.DateTimeField(blank=True, null=True)),
                ('knowledge_profile_code', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='work_order', to='platform_probe.maintenancealert')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_work_orders', to='platform_probe.employee')),
                ('mold', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='platform_probe.mold')),
            ],
            options={
                'ordering': ['-created_at', 'work_order_id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderEvent',
            fields=[
                ('event_id', models.CharField(default=apps.platform_probe.models.new_event_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=60)),
                ('event_data_json', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='platform_probe.workorder')),
            ],
            options={
                'ordering': ['occurred_at', 'created_at', 'event_id'],
            },
        ),
    ]
