# Generated by Django 5.2.17 on 2026-08-13 07:10

import apps.platform_probe.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_probe', '0002_employee_workorder_workorderevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSnapshot',
            fields=[
                ('snapshot_id', models.CharField(default=apps.platform_probe.models.new_snapshot_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('catalog_version', models.CharField(max_length=80)),
                ('items_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_snapshots', to='platform_probe.workorder')),
            ],
            options={
                'ordering': ['-created_at', 'snapshot_id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationReceipt',
            fields=[
                ('notification_id', models.CharField(default=apps.platform_probe.models.new_notification_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('recipient', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('SENT', '发送成功'), ('FAILED', '发送失败')], max_length=20)),
                ('message_id', models.CharField(blank=True, default='', max_length=160)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_receipts', to='platform_probe.workorder')),
            ],
            options={
                'ordering': ['-created_at', 'notification_id'],
            },
        ),
    ]
