# Generated by Django 5.2.17 on 2026-08-13 07:15

import apps.platform_probe.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_probe', '0003_knowledgesnapshot_notificationreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbnormalReport',
            fields=[
                ('abnormal_report_id', models.CharField(default=apps.platform_probe.models.new_abnormal_report_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('abnormal_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('inspection_results_json', models.JSONField(default=list)),
                ('client_request_id', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abnormal_reports', to='platform_probe.employee')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='abnormal_report', to='platform_probe.workorder')),
            ],
            options={
                'ordering': ['-created_at', 'abnormal_report_id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceHistory',
            fields=[
                ('history_id', models.CharField(default=apps.platform_probe.models.new_history_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('MAINTENANCE_COMPLETED', '保养完成')], max_length=40)),
                ('count_snapshot', models.BigIntegerField()),
                ('occurred_at', models.DateTimeField()),
                ('cycle_version_before', models.PositiveIntegerField()),
                ('cycle_version_after', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mold', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_history', to='platform_probe.mold')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_history_entry', to='platform_probe.workorder')),
            ],
            options={
                'ordering': ['-occurred_at', 'history_id'],
            },
        ),
        migrations.CreateModel(
            name='PauseSegment',
            fields=[
                ('pause_id', models.CharField(default=apps.platform_probe.models.new_pause_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('paused_at', models.DateTimeField()),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pause_segments', to='platform_probe.workorder')),
            ],
            options={
                'ordering': ['paused_at', 'pause_id'],
            },
        ),
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('report_id', models.CharField(default=apps.platform_probe.models.new_report_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('COMPLETE', '正常报工'), ('ABNORMAL', '异常报工')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('paused_seconds', models.PositiveIntegerField(default=0)),
                ('actual_minutes', models.PositiveIntegerField(default=0)),
                ('work_summary', models.TextField(blank=True, default='')),
                ('inspection_results_json', models.JSONField(default=list)),
                ('attachments_json', models.JSONField(default=list)),
                ('cycle_reset', models.BooleanField(default=False)),
                ('client_request_id', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_reports', to='platform_probe.employee')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='work_report', to='platform_probe.workorder')),
            ],
            options={
                'ordering': ['-created_at', 'report_id'],
            },
        ),
    ]
