# Generated by Django 5.2.17 on 2026-08-13 07:26

import apps.platform_probe.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_probe', '0005_clientrequestrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeRun',
            fields=[
                ('run_id', models.CharField(default=apps.platform_probe.models.new_probe_run_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=120)),
                ('tester', models.CharField(max_length=120)),
                ('mode', models.CharField(choices=[('STRICT', '严格模式'), ('COMPATIBILITY', '兼容模式')], max_length=30)),
                ('status', models.CharField(choices=[('RUNNING', '进行中'), ('COMPLETED', '已完成')], default='RUNNING', max_length=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at', 'run_id'],
            },
        ),
        migrations.CreateModel(
            name='ProbeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability_code', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('PASS_NATIVE', '原生通过'), ('PASS_WITH_ADAPTER', '适配通过'), ('MANUAL_VERIFIED', '人工确认'), ('EXTERNAL_REQUIRED', '需要外部能力'), ('BLOCKED', '阻塞'), ('NOT_TESTED', '未测试')], max_length=30)),
                ('request_snapshot_json', models.JSONField(default=dict)),
                ('response_snapshot_json', models.JSONField(default=dict)),
                ('evidence', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='platform_probe.proberun')),
            ],
            options={
                'ordering': ['capability_code'],
                'constraints': [models.UniqueConstraint(fields=('run', 'capability_code'), name='uniq_probe_step_per_capability')],
            },
        ),
    ]
