# Generated by Django 5.2.17 on 2026-08-13 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mold',
            fields=[
                ('mold_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('mold_name', models.CharField(max_length=200)),
                ('mold_type', models.CharField(choices=[('INJECTION', '注塑'), ('SHEET_METAL', '钣金')], max_length=32)),
                ('effective_mold_cycles', models.PositiveBigIntegerField()),
                ('baseline_effective_mold_cycles', models.PositiveBigIntegerField()),
                ('baseline_maintenance_at', models.DateTimeField()),
                ('cycle_version', models.PositiveIntegerField(default=1)),
                ('first_production_at', models.DateTimeField(blank=True, null=True)),
                ('development_tonnage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mold_category', models.CharField(blank=True, choices=[('FORMING', '成型'), ('PUNCH_BLANKING', '冲孔落料'), ('CONTINUOUS', '连续模'), ('SIDE_PANEL', '边板')], max_length=40, null=True)),
                ('mold_type_code', models.CharField(blank=True, max_length=32, null=True)),
                ('level_1_location', models.CharField(blank=True, default='', max_length=120)),
                ('level_2_location', models.CharField(blank=True, default='', max_length=120)),
                ('production_line', models.CharField(blank=True, default='', max_length=120)),
                ('output_updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', '启用'), ('INACTIVE', '停用'), ('UNDER_REPAIR', '维修中'), ('DISABLED', '禁用')], default='ACTIVE', max_length=32)),
                ('knowledge_profile_code', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'mold_type'], name='molds_mold_status_4a0507_idx'), models.Index(fields=['mold_type_code', 'mold_category'], name='molds_mold_mold_ty_e9e21b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_mold_cycles__gte', 0)), name='mold_effective_cycles_gte_0'), models.CheckConstraint(condition=models.Q(('baseline_effective_mold_cycles__gte', 0)), name='mold_baseline_cycles_gte_0'), models.CheckConstraint(condition=models.Q(('baseline_effective_mold_cycles__lte', models.F('effective_mold_cycles'))), name='mold_baseline_lte_effective'), models.CheckConstraint(condition=models.Q(('cycle_version__gte', 1)), name='mold_cycle_version_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('primary_rule_id', models.CharField(max_length=100)),
                ('matched_rule_ids_json', models.JSONField(default=list)),
                ('alert_type', models.CharField(choices=[('FORMAL_MAINTENANCE', '正式保养'), ('MANUAL', '手工')], max_length=40)),
                ('cycle_version', models.PositiveIntegerField()),
                ('cycle_mold_cycles_snapshot', models.PositiveBigIntegerField(null=True)),
                ('threshold_count', models.PositiveBigIntegerField(null=True)),
                ('trigger_reason', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', '开放'), ('CLOSED', '关闭')], default='OPEN', max_length=24)),
                ('dedupe_key', models.CharField(max_length=200, unique=True)),
                ('triggered_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mold', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='molds.mold')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'triggered_at'], name='molds_alert_status_a674f5_idx'), models.Index(fields=['mold', 'cycle_version'], name='molds_alert_mold_id_d94281_idx')],
            },
        ),
    ]
